### ISSUE TITLE
[BUG] gfycat returns 404 

### ISSUE THREAD

**Issue by TomAndJerry342** [tycrek/ass#110]
### Is there an existing Issue for this bug?

- [X] I have searched the existing issues

### Expected behavior

resource url is generated for example at domain.com/cool-cat

click on resource URL

taken to requested image

### Actual behavior

404 not found

### Steps to reproduce

Set X-Ass-Access header to gfycat
Sharex returns a weird link that has line breaks
Remove linebreaks and type URL into the browser
Ass returns 404

### ass version

0.1.1

### Deployment

Docker

### File storage

Local

### Operating system

Windows 10 Pro 19042

### Node version

16.13/0

### Storage method

Papito 

### Reverse proxy

- [X] I am using a reverse proxy

### Reverse proxy software

Cloudflared 

### Cloudflare

- [X] I am using Cloudflare

**Comment by tycrek** [comment]
Running ass locally requires using Node 14 as some dependencies are incompatible with Node 16. I would suggest switching to Node 14 instead, or using the Docker method if you require Node 16 for other things.

I'll close this for now but feel free to re-open if you encounter this on Node 14 (I have not in my testing).

**Comment by tycrek** [comment]
Wait, just reread. You are using Docker *and* Node 16? Why?
