### ISSUE TITLE
[FEATURE] Register System

### ISSUE THREAD

**Issue by MaximilianGT500** [tycrek/ass#130]
### Description

Hello, can you add a function that allows users to register and download their config and create or regenerate a token?

Thanks,
Maximilian

**Comment by tycrek** [comment]
A user registration system/config generator would be a frontend, please see [this comment](https://github.com/tycrek/ass/issues/131#issuecomment-1101645800) for details.

Currently the only way to create a new token is on the command line with `npm run new-token <username>`. I'll probably add some API routes in the future so frontend developers can easily create/modify users.
