### ISSUE TITLE
[FEATURE] Some type of gallery view for previously uploaded images

### ISSUE THREAD

**Issue by MostHated** [tycrek/ass#131]
### Description

Hey there,
    Thanks for all your hard work on this project. I tried a number of them prior to discovering this, but the relative simplicity in terms of usage, while being customizable and feature-rich at the same time is a real win in my book. All I had to do to get it working on my desktop after loading up the server-side was replace my previous flameshot script with the one you included and I was good to go. :+1: 

That said, one thing that would be great to have is some sort of gallery view that could be password protected that would simply list all previously uploaded images in a thumbnail grid. Nothing fancy (perhaps paginated at most), just functional to allow easier referencing of previous uploads so I don't have to go and bookmark every one of them in the browser, or save the links to text files.

I appreciate your time and consideration,
-MH

**Comment by tycrek** [comment]
Eventually if life settles down and I have time, I may publish a basic public frontend.
