### ISSUE TITLE
[FEATURE] Proper multi-user support

### ISSUE THREAD

**Issue by tycrek** [tycrek/ass#133]
### Description

Allow easier management of users (creating/deleting/modifying). API routes will be available for frontend devs.

**Comment by Facinorous-420** [comment]
Endpoints I believe ass should have for multi user suport:
- Create User
- Delete User
- Get All Users (Returns json of all users, if a front end maker wants to select a specific user they could use this endpoint then filter it to the username/secret key)
- Modify User (Secretkey, Username)
- Delete User (Gotta conform to UK laws)
- Delete All Users (quick way to delete all, though front end makers can simply lop through all users with the above Delete end point if you don't want to make this one)

Probably would be nice to add a key to the user object like apiReadAccess and apiWriteAccess which defaults to true on the FIRST USER MADE ONLY and can be modified to be true/false using the modify user endpoint. This will allow us to protect the APIs important routes w/o dealing with api keys. Users secretkey can be the API key.
