### ISSUE TITLE
[BUG] Title

### ISSUE THREAD

**Issue by artificialai223** [tycrek/ass#137]
### Is there an existing Issue for this bug?

- [X] I have searched the existing issues

### Expected behavior

It should display the image as it is the Direct endpoint.

### Actual behavior

https://cdn.dropcode.xyz/bleak-pessimistic-rhino/direct

It instead says { message: "Unauthorized" } with no error in server console.

### ass version

latest (git clone around 4 hours ago)

### Deployment

Manual

### File storage

S3

### Operating system

Ubuntu 20.04

### Node version

v16.5.0

### Storage method

papito

### Reverse proxy

- [X] I am using a reverse proxy

### Reverse proxy software

NGINX Proxy Manager (version unknown)

### Cloudflare

- [X] I am using Cloudflare

**Comment by artificialai223** [comment]
The file is in the S3 bucket and the /thumbnail endpoint works.

**Comment by artificialai223** [comment]
@tycrek Any help would be appreciated.

**Comment by tycrek** [comment]
Which S3 host are you using? Also, are you able to view the file on the public S3 URL (if any)? Lastly, do you have `viewDirect` enabled in your config?

**Comment by artificialai223** [comment]
viewDirect is not enabled, I am using Contabo and there is no public S3 url.

**Comment by artificialai223** [comment]
> viewDirect is not enabled, I am using Contabo and there is no public S3 url.

@tycrek

**Comment by artificialai223** [comment]
@tycrek Any response?

**Comment by tycrek** [comment]
Sorry for the delay.

ass effectively just acts as a proxy for the response from the S3 host, so what you see on the browser is what ass is receiving. There might be something misconfigured with your S3 host, or you may have to adjust how ass talks to S3.
