### ISSUE TITLE
Docker Containers unable to communicate with LAN after installation

### ISSUE THREAD

**Issue by snowbowls** [tycrek/ass#139]
Hello,
I apologize if this is result of my own ignorance but after using the docker-windows.bat file to install the software via docker-compose, all of my containers began to fail at communicating with my LAN. That is, nginx won't work if I give it an IP but will work if I give it a hostname on the same container network. I know this is more of a Docker issue than anything, but it happened after I attempted to install this software.  

If anyone can point me in a direction to figuring out if this is a Windows / Docker issue or if there's any suggestions on how to narrow down the problem, I'd appreciate it. Thank you!

For extra details on the issue:
I can connect to the containers via local IP but not through NGINX unless NGINX resolves to a hostname and not a local IP.
Sonarr / Radarr can't connect to download clients unless I give them a container IP on the same network (bridge)

**Comment by snowbowls** [comment]
UPDATE: 
I reinstalled Docker Desktop and my problem went away which means that installing ass changed some settings and I didn't know how to undo them. Any suggestions on what these changes were so I can learn from this?

**Comment by tycrek** [comment]
Sorry for the late reply.

Installing ass doesn't change any settings, you can check yourself in the deploy scripts. This sounds more like a problem with Windows Docker.
