### ISSUE TITLE
[FEATURE] Is it possible to automatically generate yyyy-mm-dd subfolders in custom uploader settings ?

### ISSUE THREAD

**Issue by jsjcjsjc** [tycrek/ass#140]
### Description

Hi
is it possible to automatically generate yyyy-mm-dd subfolders in server similar like below ?
![123.jpg](http://2ge.pics/i/2022/07/07/62c6da72ef08c.jpg)
![12345.jpg](http://2ge.pics/i/2022/07/07/62c6da73c5e0b.jpg)

Thanks in advance

**Comment by tycrek** [comment]
Hey, sorry for the late reply.

Your screenshots are broken, what was it that you wanted?

**Comment by samip5** [comment]
I think they mean that the url would end up as instance.example/2022-11-20/item-id etc?

**Comment by jsjcjsjc** [comment]
> I think they mean that the url would end up as instance.example/2022-11-20/item-id etc?



> I think they mean that the url would end up as instance.example/2022-11-20/item-id etc?

YES, you are right ;-)

**Comment by tycrek** [comment]
Gotcha, I'll try to get this into 1.14.1
