### ISSUE TITLE
[FEATURE] global admin webhook

### ISSUE THREAD

**Issue by MrInternetGitHub** [tycrek/ass#142]
### Description

make a way to log uploads through discord webhook or make a discord bot run inside ass ive seen this feature in another sharex hosting server
https://github.com/TannerReynolds/ShareX-Upload-Server

**Comment by tycrek** [comment]
This already exists for users (see the README) but I'll add a way for hosts to have a "moderators log"

**Comment by tycrek** [comment]
Completed, will be available next release. 🍑
