### ISSUE TITLE
[FEATURE] Handle /index.html route

### ISSUE THREAD

**Issue by samip5** [tycrek/ass#144]
### Description
It would be great if the app would handle requests to /index.html but still have the same logic like it currently does. 
This is for reverse-proxy workaround.

**Comment by Akenndy** [comment]
It would be great if the app would handle requests to /index.html but still have the same logic like it currently does.
This is for reverse-proxy workaround.

**Comment by tycrek** [comment]
I'm not exactly sure this is worth it, all modern browsers handle `/` as the index just fine. Which reverse proxy has an issue? I know that Nginx and Caddy both work fine with `/`.

Closing for now; if there's a compelling reason to add this I'm open to hearing it.

**Comment by samip5** [comment]
> I'm not exactly sure this is worth it, all modern browsers handle `/` as the index just fine. Which reverse proxy has an issue? I know that Nginx and Caddy both work fine with `/`.
> 
> Closing for now; if there's a compelling reason to add this I'm open to hearing it.

Apache for example while using mod_rewrite in proxy mode aka:

```
RewriteEngine On
RewriteRule ^/?(.*)$ http://10.0.0.56:40106/$1 [P]
```

**Comment by samip5** [comment]
That rewrite in my comment results in Apache always trying to request /index.html which of course doesn't work as it's not handled by the app but is the default index in Apache's configuration. This might need to be fixed in the rewrite rules rather than app though.

**Comment by tycrek** [comment]
Yeah that sounds like an Apache fix. I won't add a route myself but if you're up for editing source, you can add the below code [to Line 107 in `ass.ts`](https://github.com/tycrek/ass/blob/e7f1e2b/src/ass.ts#L107)

```ts
app.get('/index.html', (req, res, next) => res.sendStatus(201));
```
