### ISSUE TITLE
[BUG] Doesn't allow mp4 files to be uploaded in strict mode.

### ISSUE THREAD

**Issue by Sliden101** [tycrek/ass#145]
### Is there an existing Issue for this bug?

- [X] I have searched the existing issues

### Expected behavior

Upload mp4 file in strict mode and embed it.

### Actual behavior

Doesn't detect mp4 file as permitted media. Instead detects as application/octet-stream,

### Steps to reproduce

1.Turn on strict mode
2.Try to upload an mp4 file

### ass version

ass@0.11.0-rc.1

### Deployment

Manual

### Operating system

pterodactyl container supposedly debian

### Node version

17.1.0

**Comment by James-Discord** [comment]
to fix it, turn off strict mode

**Comment by tycrek** [comment]
I've determined this only occurs on Node 17, `mediaStrict: true` works fine on Node 16.
