### ISSUE TITLE
[FEATURE] Enable Discord Unix Timestamps

### ISSUE THREAD

**Issue by CyberGhost047** [tycrek/ass#149]
### Description

Allow discord timestamp syntax to be passed in &timestamp to make time correct for each user that sees it

https://gist.github.com/LeviSnoot/d9147767abeef2f770e9ddcd91eb85aa - may help when adding the feature.

**Comment by tycrek** [comment]
While this would be awesome, sadly Discord doesn't support it through web-based embeds
![image](https://user-images.githubusercontent.com/29926144/192921697-0daeb89c-6320-4b25-bee4-fe001f04b323.png)
