### ISSUE TITLE
[BUG] Error: EPERM: operation not permitted, unlink while uploading GIF files.

### ISSUE THREAD

**Issue by bditt** [tycrek/ass#153]
### Is there an existing Issue for this bug?

- [X] I have searched the existing issues

### Expected behavior

File should upload and be treated in the same way a .mp4 file is.

### Actual behavior

Response: 500
Error: EPERM: operation not permitted, unlink 'path\to\local\gif\giphy.gif'

It uploads the file, but doesn't seem to be able to return it.

I'm using the a digital oceans space storage to hold my files.

### Steps to reproduce

1. Findany gif from [https://giphy.com/](https://giphy.com/)
2. Right click it, save as, save as .gif file.
3. Right click it in file explorer, click "Upload with ShareX".
4. Check console for error.

### Logs (optional)

```text
Sep 14, 2022, 3:07 AM [EXPRESS]  HTTP POST: /
Sep 14, 2022, 3:07 AM [DEBUG]    Hash for giphy.gif: 03f352c4fbb433527c0a24fa9de861001f288368 (SHA1, hex)
Sep 14, 2022, 3:07 AM [DEBUG]    Saving file: giphy.gif (in S3)
Sep 14, 2022, 3:07 AM [DEBUG]    File saved: giphy.gif (in S3)
Sep 14, 2022, 3:07 AM [EXPRESS]  Response: 500
Error: EPERM: operation not permitted, unlink 'path\to\local\gif\giphy.gif'
```

### ass version

* ass v0.12.0 *

### Deployment

Manual

### Operating system

Windows Server 2019 version 1809

### Node version

v17.7.1

**Comment by tycrek** [comment]
Is it possible to give Node 16 LTS a shot? Node 17 seems to have a number of issues. Based on your Issue it sounds like other file types still work- do GIF's *not* from Giphy upload or do all GIF's fail?

**Comment by bditt** [comment]
I can give it a try, and it's all types of gifs, not just giphy gifs.

**Comment by bditt** [comment]
I couldn't uninstall node 17, so seems I can't try it.

**Comment by Permanently** [comment]
> I couldn't uninstall node 17, so seems I can't try it.

Try [nvm](https://github.com/nvm-sh/nvm).

**Comment by tycrek** [comment]
Closing issue until user is able to reproduce on Node 16
