### ISSUE TITLE
[QUESTION] How to get MP4's to embed on discord?

### ISSUE THREAD

**Issue by bditt** [tycrek/ass#154]
Sending them a link for them to click on is kind of sketchy, and a lot won't click on it.

Is there a way to make it so that the MP4's will be embeded on discord instead of on the site?

**Comment by bditt** [comment]
> They should automatically, as i just tested this today.

Mine always looks like this:
[http://portableabortions.com/⁠‌‌⁠⁠‍‍⁠‌​](http://portableabortions.com/⁠‌‌⁠⁠‍‍⁠‌​)

![image_2022-10-13_160227974](https://user-images.githubusercontent.com/14840526/195697997-f18bf375-5d9b-4f30-bf5e-185b90893349.png)

**Comment by bditt** [comment]
> Wierd, mine embed. [https://i.zyztem.xyz/⁠⁠​‍⁠⁠​](https://i.zyztem.xyz/%E2%81%A0%E2%81%A0%E2%80%8B%E2%80%8D%E2%81%A0%E2%81%A0%E2%80%8B) ![image](https://user-images.githubusercontent.com/66957203/195698494-730a3923-47b4-4d48-be7a-29f1736b8330.png) ‌‌⁠​​

Hm.... this is my config.json

Tell me if you see anything wrong.

```json
{
    "host": "0.0.0.0",
    "port": 80,
    "domain": "portableabortions.com",
    "maxUploadSize": 1000,
    "isProxied": false,
    "useSsl": false,
    "resourceIdSize": 10,
    "resourceIdType": "zws",
    "spaceReplace": "-",
    "gfyIdSize": 2,
    "mediaStrict": false,
    "viewDirect": false,
    "dataEngine": "@tycrek/papito",
    "frontendName": "ass-x",
    "useSia": false,
    "s3enabled": true,
    "s3endpoint": "nyc3.digitaloceanspaces.com",
    "s3bucket": "bditts-sharex-files",
    "s3usePathStyle": false,
    "s3accessKey": "secret",
    "s3secretKey": "secret",
    "__WARNING__": "The following configs are no longer used and are here for backwards compatibility. For optimal use, DO NOT edit them.",
    "diskFilePath": "uploads/",
    "saveWithDate": true,
    "saveAsOriginal": false
}

```

**Comment by bditt** [comment]
> @bditt I would be interested to see what happens if you used HTTPS. I can understand Discord blocking embeds from insecure resources though I don't have proof of that.

I see, I'm not really sure how to setup https, since I'm just hosting this on a small vps I got.

If you don't mind explaining real quick on how to set it up, I'd really appreciate it!

**Comment by tycrek** [comment]
I have a link to my tutorial in [the README](https://github.com/tycrek/ass#using-https)

**Comment by bditt** [comment]
> I have a link to my tutorial in [the README](https://github.com/tycrek/ass#using-https)

Ah. Saw that, but my VPS is a windows vps, but thanks for the tutorial anyway.

**Comment by bditt** [comment]
> Then I suggest cloudflare tunnels.

Thanks!

Also, want to say, images embed even though SSL is disabled.

So I don't get why SSL would change MP4's.

**Comment by tycrek** [comment]
> So I don't get why SSL would change MP4's.

I'm not sure either but that's the only significant part of your config that's a bit different from a typical production setup.

I do see you're using S3, *but* it's Digital Ocean Spaces, which I know work fine with ass (used them myself previously). With that said, maybe try setting S3 to `false` just temporarily as a test.

**Comment by bditt** [comment]
> I'm not sure either but that's the only significant part of your config that's a bit different from a typical production setup.
> 
> I do see you're using S3, _but_ it's Digital Ocean Spaces, which I know work fine with ass (used them myself previously). With that said, maybe try setting S3 to `false` just temporarily as a test.

Turning it off did not fix my issue.

Maybe I need to reinstall "ass" again and set it up all over again.
