### ISSUE TITLE
[FEATURE] Use NanoID

### ISSUE THREAD

**Issue by tycrek** [tycrek/ass#158]
### Description

Check out [NanoID](https://evilmartians.com/opensource/nanoid)

**Comment by Recontaminated** [comment]
Is there an issue with the current ID system or speed improvement?

**Comment by tycrek** [comment]
Nano ID was added in https://github.com/tycrek/ass/pull/177/commits/62dae23681c909cf13df15a8ec2966e0c9d652e9 / https://github.com/tycrek/ass/pull/177/commits/d93fda89d6c58e0902e52ff896f5741b18fc7f19 and will be included in **0.14.0**
