### ISSUE TITLE
[FEATURE] Large video embeds not working

### ISSUE THREAD

**Issue by nischay876** [tycrek/ass#165]
### Description

maybe use https://streamable.com/ video embed concept that's easy to copy

**Comment by tycrek** [comment]
I'm not sure what your requesting as they just use [Open Graph](https://ogp.me/) and [oEmbed](https://oembed.com/). I actually built ass using Streamables OGP and oEmbed.

Closing since this is how ass already works; if you have a real solution for large video sizes feel free to let me know.
