### ISSUE TITLE
[FEATURE] Option to auto remove links in Discord

### ISSUE THREAD

**Issue by iTzEthqnHD** [tycrek/ass#168]
### Description

You told me to open this issue lol. Link to Discord message: https://discord.com/channels/848274994375294986/848313252009869312/1040146484575879198

**Comment by tycrek** [comment]
Should be possible with a direct view option for Discord, skipping Open Graph and oEmbed. I'll try to get on this tomorrow

**Comment by tycrek** [comment]
Sorry I never got to this; I'll plan it for 0.15.0 (complete rewrite), closing this issue in favor of #215
