### ISSUE TITLE
[FEATURE] Support Storj S3 host

### ISSUE THREAD

**Issue by tycrek** [tycrek/ass#172]
### Description

[Storj](https://www.storj.io/) is an affordable high-performance S3 host. Many users could benefit from compatibility.

**Comment by nischay876** [comment]
https://aws.amazon.com/blogs/developer/generate-presigned-url-modular-aws-sdk-javascript/
https://stackoverflow.com/questions/38831829/nodejs-aws-sdk-s3-generate-presigned-url

example 1 code - 
```import { HttpRequest } from "@aws-sdk/protocol-http";
import { S3RequestPresigner } from "@aws-sdk/s3-request-presigner";
import { parseUrl } from "@aws-sdk/url-parser";
import { Sha256 } from "@aws-crypto/sha256-browser";
import { Hash } from "@aws-sdk/hash-node";
import { formatUrl } from "@aws-sdk/util-format-url";
// ...
const s3ObjectUrl = parseUrl(`https://${bucket}.s3.${region}.amazonaws.com/${key}`);
const presigner = new S3RequestPresigner({
    credentials,
    region,
    sha256: Hash.bind(null, "sha256"), // In Node.js
    //sha256: Sha256 // In browsers
});
// Create a GET request from S3 url.
const url = await presigner.presign(new HttpRequest(s3ObjectUrl));
console.log("PRESIGNED URL: ", formatUrl(url));```

example code 2 -
```
    AWS.config.update({ 
        accessKeyId: ':)))',
        secretAccessKey: ':DDDD',
        region: 'ap-south-1',
        signatureVersion: 'v4'
    });
    const s3 = new AWS.S3()
    const myBucket = ':)))))'
    const myKey = ':DDDDDD'
    const signedUrlExpireSeconds = 60 * 5

    const url = s3.getSignedUrl('getObject', {
        Bucket: myBucket,
        Key: myKey,
        Expires: signedUrlExpireSeconds
    });
    console.log(url);
```

**Comment by nischay876** [comment]
https://github.com/nischay876/ass/commit/6c03fceb2a1d45c4fe7aa7a9dbdc877fea25ed42

**Comment by tycrek** [comment]
Planning for 0.15.0. Closing this issue in favor of #216
