### ISSUE TITLE
[FEATURE] Allow embeds to be customised server-side

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [tycrek/ass#173]
### Description
Allow embeds for images to be created server-side instead of client-side.

Something like this:

File named `embed.json` with customisable options, so when a file is uploaded it would have an embed when pasted in Discord or somewhere without having to add the headers in ShareX.

Example:
```json
{
    "color": "#123456",
    "title": "title here",
    "description": "description here"
}
```

**Comment by tycrek** [comment]
added/adding in 0.14.0
