### ISSUE TITLE
[BUG] Something wrong with website.

### ISSUE THREAD

**Issue by davidnjoy** [tycrek/ass#178]
### Is there an existing Issue for this bug?

- [X] I have searched the existing issues

### Expected behavior

I found a bug something. that I made the capture and there the website did not come out well but in discord as well. I give a preview picture

### Actual behavior

![Discord_dOVRgfgpis](https://user-images.githubusercontent.com/63205665/205308390-de8fa4be-d45f-430b-8cec-7703b1833d9f.png) Good, but in website. didn't well good. 
Website: ![chrome_0UCumzlbFK](https://user-images.githubusercontent.com/63205665/205308469-0c245bed-945b-4f62-899b-04ad27e5121c.png)

### ass version

0.13.0 (latest)

### Deployment

Manual

### Operating system

Ubuntu 20.04

### Node version

v18.12.1

**Comment by tycrek** [comment]
This is resolved in https://github.com/tycrek/ass/commit/dcd93b6fc3ed921d746dfcf76ad4acc2ad218df5
