### ISSUE TITLE
[FEATURE] Option to use generated file names

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [tycrek/ass#181]
### Description

Add an option to the `config.json` file so instead of using the original file name for the title on the viewing page and things, it uses the generated file name instead.

Currently it is like this:
![image](https://user-images.githubusercontent.com/87287585/207787637-1b11eef8-92f8-4a0a-b44c-619d04ecdf7c.png)

But I would like an option to make it like this:
![image](https://user-images.githubusercontent.com/87287585/207788277-a1df250d-8b2a-4b83-94fd-76cad965022b.png)

**Comment by tycrek** [comment]
I can probably do this but I'm curious what the reason is?

**Comment by WilliamDavidHarrison** [comment]
> I can probably do this but I'm curious what the reason is?

I don't like to use the original file name just the generated one so they all match sort of.

**Comment by tycrek** [comment]
Fair enough, I'll add that to https://github.com/tycrek/ass/tree/0.14.0/stage

**Comment by tycrek** [comment]
GitHub automations failing again, ugh. This was added/adding in 0.14.0
