### ISSUE TITLE
Link to the Caddy tutorial is broken

### ISSUE THREAD

**Issue by captainabap** [tycrek/ass#200]
I would like to use Caddy but I am not sure, what to write to the Caddyfile for the reverse-proxy to ass. Can you give me a hint or correct the link to your tutorial.

**Comment by tycrek** [comment]
Yeah I have to either rewrite it or point to the official docs as they're usually sufficient now.

As long as you're able to install Caddy and get it running, you can use this as a simple baseline:

![image](https://user-images.githubusercontent.com/29926144/214977923-b45d4d1e-c656-41a2-9fdf-013bad413614.jpeg)

**But do not include the `import` line!** Unless you know how to configure Cloudflare for Authenticated Origin Pulls and Strict mode, then let me know and I'll provide the snippet for that.

**Comment by captainabap** [comment]
Thanks a lot. The information solved my problem!
