### ISSUE TITLE
[QUESTION] How the Markdown rendering works ?

### ISSUE THREAD

**Issue by Smallinger** [tycrek/ass#205]
Hey, i want to ask how the Markdown rendering works ?
if i have "viewDirect": false, in my config i see only 
![direct](https://user-images.githubusercontent.com/8080568/221021086-c44b0224-d276-4f71-9471-6e6bfcfbbc65.png)

"viewDirect": true,
he download instant the direct as a binary file.
![direct](https://user-images.githubusercontent.com/8080568/221021392-c59050cb-14ac-4650-95f4-243dbd278f34.png)

**Comment by tycrek** [comment]
Currently ass isn't set up to display Markdown files. I'll aim to add this feature in 0.15.0
