### ISSUE TITLE
[FEATURE] Publish docker image to container registry

### ISSUE THREAD

**Issue by MPThLee** [tycrek/ass#219]
### Description

It's easier and automate to update container. Simply run `docker pull` with latest tag, and restart it will update automatically.

Honestly, I don't want to run `git pull` every update. I usually using [watchtower](https://github.com/containrrr/watchtower) to update containers automatically.

There's github actions to help this setup. [build-push-action](https://github.com/docker/build-push-action), [setup-buildx-action](https://github.com/docker/setup-buildx-action) and [login-action](https://github.com/docker/login-action).

There's also free registry for github: [ghcr.io](https://github.com/features/packages)

**Comment by tycrek** [comment]
I'll try to get this working for the 0.15.0 rewrite (fully rewritten, web-based setup after deployment).

**Comment by Uruknara** [comment]
Same as me really making a docker image would the best way to deploy ass

**Comment by tycrek** [comment]
This has been completed in `dev/0.15.0`. See [tycrek/ass](https://hub.docker.com/r/tycrek/ass) on Docker Hub.

**Comment by tycrek** [comment]
*For context ass 0.15.0 is NOT production ready, but the Docker deploy is more or less completed.
