### ISSUE TITLE
Image preview not showing in Discord

### ISSUE THREAD

**Issue by Zibbp** [tycrek/ass#26]
When linking to an image post in Discord the image is not shown in Discord. I'm able to have Discord display the image if I link the raw image using `/direct`. Video support does work though, If I link a video post Discord displays the video inline.

Is there a specific header that I need to apply in ShareX to allow the image to be displayed without appending `/direct`?

**Comment by tycrek** [comment]
Should work fine for images both with and without Embeds, just did for me:

![discord embeds](https://ass.rip/oMXJ60dBlXP0/direct)

Just released [0.7.4](https://github.com/tycrek/ass/releases/tag/releases/0.7.4), let me know if it works for you

**Comment by Zibbp** [comment]
It was a configuration error on my side. I had accidentally set useSSL to false in the config. After changing that to true it works. Thanks for the speedy reply!

**Comment by tycrek** [comment]
Ahhh gotcha, glad it's figured out. And no problem
