### ISSUE TITLE
Use as Docker container

### ISSUE THREAD

**Issue by tycrek** [tycrek/ass#3]

**Comment by Zusier** [comment]
Got a docker image working!
![LORahNrR2e](https://user-images.githubusercontent.com/46111482/125362612-b6e7af00-e35e-11eb-9603-e85907750c07.png)
 I'm not the best at making docker images, but here it is:
 ```
FROM node:14.17.3
WORKDIR /usr/src/ass
# Copy directory files (config.json, source files etc.)
COPY . ./
# update npm
RUN npm install npm@latest -g
# Install dependencies
RUN npm i
# Expose web port
EXPOSE 40115
# start ass
RUN npm start
```
A caveat is you will need to have a `config.json` file setup before deploying. Can probably fix via ENV variables but as I said I'm not the best with this stuff 😆

Love the degoogle project btw, good work!

**Comment by tycrek** [comment]
Awesome work, thanks for attempting this!

> will need to have a config.json file setup before deploying

This might be solvable with a script in `package.json`, like `npm run install-docker`. Then the process for setup would be:

```bash
git clone {repo} && cd ass/
npm run install-docker
```

in `package.json`:

```json
"install-docker": "npm i && npm run setup && LOOK_HERE",
"docker-start": "...",
"docker-stop": "...",
"docker-restart": "...",
```

**`LOOK_HERE`** - I'm not sure what command you ran to get the container running, but that would be substituted here. If it's a few commands then maybe a bash script.

I *think* that would work, not really sure. I assume Docker opens port `40115`, so the reverse proxy can still reference that port.

> Love the degoogle project btw

Haha glad you like it :D

**Comment by Zusier** [comment]
Revised so it can be built then deployed:
```
FROM node:14.17.3
WORKDIR /usr/src/ass
# Copy directory files (config.json, source files etc.)
COPY . ./
# update npm, need >=7
RUN npm install npm@latest -g
# Install dependencies
RUN npm i
# start ASS
CMD npm start
```
> LOOK_HERE - I'm not sure what command you ran to get the container running, but that would be substituted here. If it's a few commands then maybe a bash script.

It would need two commands:
```
# Build the image (locally named as "ass"
docker build -t ass .
# Deploy image and map web port
docker run -p 40115:40115 -d ass
```
So...
`"install-docker": "npm i && npm run setup && docker build -t ass . && docker run -p 40115:40115 -d ass",`
>  I assume Docker opens port 40115

Yep, note the `EXPOSE` line within the docker file, that opens the port, then in the command the port will be mapped so it can be used by the reverse proxy

**Comment by Zusier** [comment]
As for volumes:

`docker run -p 40115:40115 --name ass --volume=/PATH/TO/UPLOADS:/Uploads -d ass`

Unfortunately it must be an absolute path, so it would have to be set by the user or ask for input similar to the setup script?

**Comment by tycrek** [comment]
Hmmm, a bash script would probably work best then so it can ask for user input there. Maybe Docker Compose, but I'm not super familiar with Docker

**Comment by Zusier** [comment]
```
version: "3.9"
services:
  ass:
    build: .
    ports:
      - "40115:40115"
    volumes:
      - /root/DComp/ass/Uploads:/Uploads
```
   
Can be built and deployed via `docker-compose up -d`

**Comment by tycrek** [comment]
Awesome, I'll try that out myself in a bit. Thanks for doing that!

**Comment by tycrek** [comment]
@Zusier After some playing around and reading through the Docker docs for most of today, [here's what I came up with](https://github.com/tycrek/ass#docker-compose). I already have some plans on making it a bit more streamlined.

My testing with this process was successful for this config, I have not tried any others yet:

- No SSL
- No reverse proxy
- No custom frontend
- Default JSON data storage
- Local file storage

`Dockerfile`: https://github.com/tycrek/ass/blob/master/Dockerfile
`compose.yaml`: https://github.com/tycrek/ass/blob/master/compose.yaml

Good news: it's usable now, so I'll close this issue! Thanks for helping get that off the ground 😄

**Comment by Zusier** [comment]
No problem! 

One thing I saw that was odd to me was that the compose file is named `compose.yaml`? The native file name would be: docker-compose.yml/yaml

![PUTTY_DJHXM6Jajn](https://user-images.githubusercontent.com/46111482/125558652-858e0f79-7403-4320-b47a-6bd8f3b383f5.png)

**Comment by tycrek** [comment]
> No problem! 
> 
> One thing I saw that was odd to me was that the compose file is named `compose.yaml`? The native file name would be: docker-compose.yml/yaml
> 
> ![PUTTY_DJHXM6Jajn](https://user-images.githubusercontent.com/46111482/125558652-858e0f79-7403-4320-b47a-6bd8f3b383f5.png)
> 

Oh, I thought the spec said `compose.yaml` was standard..? I'll check again and comment back
