### ISSUE TITLE
Discord bot control (optional)

### ISSUE THREAD

**Issue by tycrek** [tycrek/ass#5]

**Comment by J9G** [comment]
Hello i have made a bot to upload to this if that is what you are asking? https://discord.gg/4kUKU5Pg that is my discord server yvngxmonkey#0016 add me on cord and we can work out i have 292 friend req so i dont check add so u have mutual server so u can msg

**Comment by tycrek** [comment]
Decided to leave this for other devs to implement themselves. The primary goal of ass is to provide a strong backend for devs to build a frontend around, and Discord bots are something I'd consider frontend.
