### ISSUE TITLE
[BUG] Resource identifier doesn't check existing indentifiers

### ISSUE THREAD

**Issue by Metacinnabar** [tycrek/ass#75]
### Is there an existing Issue for this bug?

- [X] I have searched the existing issues

### Expected behavior

When generating a unique key for an image a check should be performed to see if any previous images have generated the same key.

### Actual behavior

A duplicate key can be generated resulting in the image upload failing.

### Steps to reproduce

1. Screenshot and upload to ass.
2. Repeat step 1 until logs show `Error: Key already exists`.

### Logs (optional)

```text
Oct 2, 2021, 12:39 AM [ERROR]    Error: Key already exists
Error: Key already exists
    at @tycrek/papito/JsonDataEngine.js:66:13
    at new Promise (<anonymous>)
    at JsonPutFunc (@tycrek/papito/JsonDataEngine.js:63:9)
    at JsonDataEngine.put (@tycrek/papito/DataEngine.js:55:29)
    at /routers/upload.js:70:7
    at Layer.handle [as handle_request] (express/lib/router/layer.js:95:5)
    at next (express/lib/router/route.js:137:13)
    at Route.dispatch (express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (express/lib/router/layer.js:95:5)
    at express/lib/router/index.js:281:22
Oct 2, 2021, 12:39 AM [Express] Response: 500
```

### ass version

0.8.6

### Deployment

Manual

### File storage

Local

### Operating system

Ubuntu 20.04.2 LTS

### Node version

14.17.1

### Reverse proxy

- [X] I am using a reverse proxy

### Reverse proxy software

nginx/1.18.0 (Ubuntu) 

### Cloudflare

- [ ] I am using Cloudflare

**Comment by tycrek** [comment]
👍 thanks for reporting, I'll look into that soon

Oct. 1, 2021, 8:52 a.m. by ***@***.***:
